on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development
  workflow_dispatch:

jobs:
  test:
    if: github.actor != 'dependabot[bot]' && github.ref != 'refs/heads/master'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python and uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install TA-lib C library and dependencies
        shell: bash
        run: |
          # Build TA-Lib C library
          wget https://raw.githubusercontent.com/mrjbq7/ta-lib/master/tools/build_talib_from_source.bash
          chmod +x build_talib_from_source.bash
          ./build_talib_from_source.bash ${{ github.workspace }}/dependencies

          # Set environment variables for TA-Lib Python package build
          export TA_INCLUDE_PATH=${{ github.workspace }}/dependencies/include
          export TA_LIBRARY_PATH=${{ github.workspace }}/dependencies/lib

          # Install all dependencies, including TA-Lib Python package
          uv pip sync requirements.lock

      - name: Install polars-ti
        run: uv pip install --no-deps -e .

      - name: Run tests
        run: make tests
